learning_templates/basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from basic_app import views

#Template tagging
app_name = 'basic_app' # say django check in basic _app & find url

urlpatterns= [
    path('relative/',views.relative,name='relative'),
    path('other/',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import url,include

urlpatterns = [
    path('',views.index,name='index'),  #for index
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title></title>
    <link rel="stylesheet"href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <meta charset="utf-8">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index'%}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other'%}">Other</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!--Anything outside of this will be inherited if u extend that-->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
 {% block body_block %}
 <html lang="en" dir="ltr">
   <head>
     <meta charset="utf-8">
   <h1>Welcome to index</h1>
   <a href="{% url 'basic_app:relative'%}">index to relative</a>
   <h1>This is a Home picture</h1>
 </head>
 </body>
</html>

 {% endblock %}







<!--
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>This is index</h1>
    <a href="{% url 'basic_app:relative' %}">index to relative</a>
  </body>
</html>
-->

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
 {% extends "basic_app/base.html" %}
  {% block body_block %}

   <h1>Other template inheritance</h1>
   <h2>This is an example of inheritance</h2>
   <a href="{% url 'basic_app:relative' %}">move to index</a>
  {% endblock %}



<!--
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to other</h1>
    <a href="{% url 'basic_app:relative' %}">move to index</a>
  </body>
</html>
-->

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to relative templates</h1>
    <a href="{% url 'basic_app:other' %}">Move to Other</a></br>
    <a href="{% url 'admin:index' %}">Move to admin</a></br>
    <a href="{% url 'index' %}">move to index page</a>
  </body>
</html>